<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Fetchle.Cli\Fetchle.Cli.csproj" />
    <ProjectReference Include="..\Fetchle.Fixtures\Fetchle.Fixtures.csproj" />
  </ItemGroup>
</Project>
